services:
  - type: web
    name: thumb-up-on-canvas
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: thumb-up-postgres
          property: connectionString

databases:
  - name: thumb-up-postgres
    databaseName: thumbs
    user: thumbs
    plan: free
